### ISSUE TITLE
Error: Cannot read properties of undefined (reading '__STORYBOOK__')

### ISSUE THREAD

**Issue by orsileonel** [nuxt-modules/storybook#583] opened 2024-05-07 22:25 UTC
Hello! 👋

I just installed Nuxt Storybook using the `npx nuxi@latest module add storybook` command, everything completed successfully until I ran `yarn dev` where I got `ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading '__STORYBOOK__')`.

Actual configuration:

**NodeJS:** v20.12.2

**Yarn:** v4.2.1

**package.json**
```
"dependencies": {
    "@nuxtjs/storybook": "^8.0.0",
    "nuxt": "^3.11.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@nuxt/eslint": "^0.3.10",
    "@nuxtjs/i18n": "^8.3.1",
    "@nuxtjs/seo": "^2.0.0-rc.10",
    "@nuxtjs/stylelint-module": "^5.2.0",
    "@nuxtjs/tailwindcss": "^6.12.0",
    "eslint": "^9.2.0",
    "eslint-plugin-vuejs-accessibility": "^2.3.0",
    "husky": "^9.0.11",
    "lint-staged": "^15.2.2",
    "nuxt-font-loader": "^2.3.5",
    "postcss-html": "^1.6.0",
    "postcss-scss": "^4.0.9",
    "prettier": "^3.2.5",
    "prettier-plugin-tailwindcss": "^0.5.14",
    "stylelint": "^16.5.0",
    "stylelint-order": "^6.0.4",
    "typescript": "^5.4.5",
    "vite-plugin-eslint2": "^4.4.0"
  }

```

Thank you.

**Comment by tobiasdiez** [comment] 2024-05-08 02:15
Duplicate of https://github.com/nuxt-modules/storybook/issues/538

**Closed by tobiasdiez** 2024-05-08 02:15 UTC
