### ISSUE TITLE
Latest version Broken

### ISSUE THREAD

**Issue by Renato66** [nuxt-modules/storybook#598] opened 2024-05-15 12:42 UTC
check the https://storybook.nuxtjs.org/examples/basic
<img width="950" alt="image" src="https://github.com/nuxt-modules/storybook/assets/9284273/10dba097-ac28-452c-bd63-7914906aa75a">

**Comment by volovar** [comment] 2024-05-16 18:30
I'm having this issue too, looks like it's been fixed in the main branch but isn't in the `v8.0.0` release. It can't find `__STORYBOOK__` on `import.meta.env` since env is undefined
It's fixed here: [v8.0.0...main](https://github.com/nuxt-modules/storybook/compare/v8.0.0...main#diff-030fc083b2cbf5cf008cfc0c49bb4f1b8d97ac07f93a291d068d81b4d1416f70R53)

**Comment by tobiasdiez** [comment] 2024-05-17 07:21
Duplicate of #538.

@chakAs3 could you please release a new version? (refs #562)

**Closed by tobiasdiez** 2024-05-17 07:21 UTC
