### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by RodrigoReyes-vw** [nuxt-modules/storybook#751] opened 2024-08-12 16:26 UTC
Hi, I'm getting this error on a fresh nuxt install as well as the examples, I'm using NPM and PNPM and can't fix it

`Failed to fetch dynamically imported module: http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/@storybook_vue3_dist_entry-preview__mjs.js?v=0ac1eac7`

Versions: 
"@nuxtjs/storybook": "^8.1.5",
    "@storybook/addon-essentials": "^8.2.8",
    "@storybook/addon-interactions": "^8.2.8",
    "@storybook/addon-links": "^8.2.8",
 "@storybook/builder-vite": "^8.2.8"

**Comment by tobiasdiez** [comment] 2024-08-12 18:01
Duplicate of https://github.com/nuxt-modules/storybook/issues/731

**Closed by tobiasdiez** 2024-08-12 18:01 UTC
