### ISSUE TITLE
Context conflict 

### ISSUE THREAD

**Issue by ademyalcin27** [nuxt-modules/storybook#768] opened 2024-08-28 08:59 UTC
Im getting Error: Context conflict, when i write 2 stories in a file with autodoc. Im trying to write [CSF](https://storybook.js.org/docs/api/csf) but it doesn't work. Does anyone have any ideas?

![Screenshot 2024-08-28 at 10 56 35](https://github.com/user-attachments/assets/b1b1a550-5261-4ade-8b45-b44f7bff1552)

https://stackblitz.com/edit/nuxt-starter-ga2at1?file=.storybook%2Fmain.ts

**Comment by tobiasdiez** [comment] 2024-08-28 09:19
Duplicate of https://github.com/nuxt-modules/storybook/issues/661 (and already fixed in main)

**Closed by tobiasdiez** 2024-08-28 09:19 UTC
