### ISSUE TITLE
SyntaxError: Identifier '_toDisplayString' has already been declared

### ISSUE THREAD

**Issue by SteinRobert** [nuxt-modules/storybook#428] opened 2023-09-26 13:55 UTC
This happens when using Nuxt 3.6.5 with this module.
Based on the examples from the docs (where this happens as well).
```
SyntaxError: Identifier '_toDisplayString' has already been declared
```

See this example:
https://storybook.nuxtjs.org/examples/pinia

It throws `Identifier '_createElementVNode' has already been declared`.

Could be it has something to do with nuxt 3.7.x. When I downgrade the dependency in the example it seems to work.

**Comment by matthiasobergasser** [comment] 2023-09-29 09:25
+1

**Comment by danielroe** [comment] 2023-11-06 09:50
This looks to me like `@vitejs/plugin-vue` might be injected twice (and therefore transforming components twice).

https://github.com/storybookjs/storybook/blob/0ca0061c3fde053830aa1b5bdc0fce54776e1e13/code/frameworks/vue3-vite/src/preset.ts#L20-L23

That is because Nuxt injects this plugin after `vite:extendConfig` is resolved (to allow users customising the options):

https://github.com/nuxt/nuxt/blob/38b6d88cfab3477edabfa37d6f97b95eefc6ae6c/packages/vite/src/client.ts#L142-L149

Histoire solves the issue like this: https://github.com/histoire-dev/histoire/blob/main/packages/histoire-plugin-nuxt/src/index.ts#L172-L181

**Comment by JulianMar** [comment] 2023-11-08 10:59
If that would be the case, couldn't we check this by using the `vite:configResolved` hook, right? If I understand it correctly there the `@vitejs/plugin-vue` should show up twice. 
I tried it in here and it's not showing up twice. https://stackblitz.com/edit/nuxt-starter-m6xpys?file=nuxt.config.ts

**Comment by chakAs3** [comment] 2023-11-08 12:42
> If that would be the case, couldn't we check this by using the `vite:configResolved` hook, right? If I understand it correctly there the `@vitejs/plugin-vue` should show up twice. I tried it in here and it's not showing up twice. https://stackblitz.com/edit/nuxt-starter-m6xpys?file=nuxt.config.ts

im fixing it now

**Comment by bmulholland** [comment] 2023-11-08 12:53
@chakAs3 FYI, I tried fixing the bug by removing the vite plugin include from `node_modules/@storybook/vue3-vite/dist/preset.js`. Not only did that not fix it, it actually stopped compiling the output at all. Super weird: either you end up with double-compiled, or no compilation.

**Comment by bmulholland** [comment] 2023-11-08 13:32
I downloaded an exact copy of the StackBlitz repro and get a different error locally:

Error: [nuxt] instance unavailable
  at useRuntimeConfig (/node_modules/.pnpm/nuxt@3.7.4_@types+node@18.17.5/node_modules/nuxt/dist/app/nuxt.js?v=e8b2d187:180:27)
  at setup (/components/Test.vue:7:32)

When running storybook in my actual codebase, I get the double compilation errors discussed above. However, those errors cannot be fixed by downgrading Nuxt to 3.6. 
So:
1. No version of Nuxt 3 and Nuxt Storybook work together on my actual codebase.
2. The StackBlitz reproduces the error I get in my codebase on all versions of Nuxt/Storybook.
3. The same code locally produces a different error, and it does go toggle on/off when using Nuxt 3.6 vs 3.7.

That's all I can do today.

**Comment by bmulholland** [comment] 2023-11-08 16:26
This is probably also https://github.com/nuxt-modules/storybook/issues/442

**Comment by filiphazardous** [comment] 2023-11-15 16:02
> @chakAs3 FYI, I tried fixing the bug by removing the vite plugin include from `node_modules/@storybook/vue3-vite/dist/preset.js`. Not only did that not fix it, it actually stopped compiling the output at all. Super weird: either you end up with double-compiled, or no compilation.

I too have been digging around, sprinkling console.logs throughout the packages in node_modules. The errors are raised by esbuild, which AFAICT isn't a dependency of vite or nuxt. I'll investigate further, to see what I come up with.

**Comment by filiphazardous** [comment] 2023-11-16 17:10
I keep hacking away at this, and these are my findings so far:
In `@vitejs/plugin-vue` there's a function called `transformMain` that raises the error. First it generates code in a variable called `output`, that is then joined into `resolvedCode`. Finally `transformWithEsbuild` is called on `resolvedCode` to transpile the TypeScript parts.

However, the code handed to `transformWithEsbuild` is already fairly well transpiled by the previous calls made by `transformMain`, and so `transformWithEsbuild` raises the error.

I'm still not sure how to fix the problem. Apparently `@vitejs/vue-plugin` works well in nearly every case - I don't understand why we are the only ones bitten by the plugin. Still, it's a pretty good lead - so I thought I'd share it here before I finish out today's work.

**Comment by filiphazardous** [comment] 2023-11-20 09:55
Next update:  
I found more problems, and don't think the update is the problem anymore. 
1. `resolveScript` in `@vitejs/plugin-vue` at some points returns code with double imports. Hooking up the debugger to node, it seemed to have a connection with using cached data.
2. Removing cache from the equation, I started getting errors about there not being any Vue context, and Vue falling back to shared context)
3. Setting Nuxt up in the storybook module, I added `console.error` to all the catches in `@storybook-vue/nuxt` preview. And it caught errors about double definitions of `_block` on the `import'#app/entry')`. This means Nuxt never actually got set up properly.

I am most definitely way out of my comfort zone here, and am starting to look for workarounds (eg just using `@storybook/vue3` instead), unless somebody has some insights?

**Comment by bmulholland** [comment] 2023-11-20 10:25
@filiphazardous You could try messaging Daniel Roe on the Nuxt Discord -- he previously offered to pair with me in debugging this issue.

For me, this was the straw the broke the camel's back, and we'll be dropping Nuxt along with our Vue 2 -> 3 upgrade.

**Comment by chakAs3** [comment] 2023-11-22 11:16
Hi @bmulholland @filiphazardous  please try the latest release of @storybook-vue/nuxt, it is working now with latest version of nuxt 3.8.1,  i did not get time to update the examples. so if you could do it. i will be thankful for you.

**Comment by filiphazardous** [comment] 2023-11-24 08:08
@chakAs3 The new version works much better. Thanks!

**Comment by chakAs3** [comment] 2023-11-25 17:18
> @chakAs3 The new version works much better. Thanks!
Welcome, Glad to hear that.

**Comment by tobiasdiez** [comment] 2024-05-02 04:45
If `@vitejs/plugin-vue` is really the underlying reason for this issue, then the recent storybook update to v8 might have resolved it already. There were also some related changes in https://github.com/storybook-vue/storybook-nuxt/pull/95.

Is still issue still present?

**Comment by tobiasdiez** [comment] 2024-08-11 20:01
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Closed by tobiasdiez** 2024-08-11 20:01 UTC
Labels: type: bug, status: needs reproduction
