### ISSUE TITLE
Error: Cannot find @storybook/vue3-vite

### ISSUE THREAD

**Issue by erikahumadakandc** [nuxt-modules/storybook#798] opened 2024-10-02 16:08 UTC
### Environment

```ZSH
❯ npx nuxi info
Working directory: /home/projects/nuxt-starter-feh3pr                         11:03:39 AM
Nuxt project info:                                                            11:03:39 AM

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

                                                                              11:03:39 AM
👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com

❯ npx envinfo --system --binaries --browsers --npmPackages

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @nuxtjs/storybook: 7.0.2 => 7.0.2 
    @storybook-vue/nuxt: 0.2.6 => 0.2.6 
    @storybook/addon-essentials: 8.0.8 => 8.0.8 
    @storybook/addon-interactions: 8.0.8 => 8.0.8 
    @storybook/addon-links: 8.0.8 => 8.0.8 
    @storybook/blocks: 8.0.8 => 8.0.8 
    @storybook/builder-vite: 8.0.8 => 8.0.8 
    @storybook/test: 8.0.8 => 8.0.8 
    @storybook/vue3: 8.0.8 => 8.0.8 
    @types/node: ^18.17.5 => 18.19.54 
    nuxt: ^3.13.2 => 3.13.2 
    storybook: 8.0.8 => 8.0.8 
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-feh3pr

### Describe the bug

I installed Storybook by running this command in a new Nuxt3 project
- `npx storybook-nuxt init`

Then I ran the command `npm run storybook`

but it is throwing this error 

```ZSH
❯ npm run storybook

> storybook
> storybook dev --port 6006

@storybook/cli v8.0.8

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
info => Starting manager..
info => Starting preview..
=> Failed to build the preview
Error: Cannot find @storybook/vue3-vite,
    at getPackageDir (./node_modules/@storybook-vue/nuxt/dist/preset.cjs:6805:9)
    at getStorybookViteConfig (./node_modules/@storybook-vue/nuxt/dist/preset.cjs:6767:64)
    at Object.viteFinal (./node_modules/@storybook-vue/nuxt/dist/preset.cjs:6773:51)
    at eval (./node_modules/@storybook/core-common/dist/index.js:12:1162)
    at s (./node_modules/envinfo/dist/envinfo.js:1:66401)
    at eval (./node_modules/envinfo/dist/envinfo.js:1:66546)
    at u (./node_modules/envinfo/dist/envinfo.js:1:56766)
    at processTicksAndRejections (node:internal/process/task_queues:192:998)
    at _0x41ac03 (https://nuxtstarterfeh3pr-1cjg.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:506247)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

### Additional context

I tried to install the missing package but it didn't work, it throws this error

```ZSH
❯ npm i --save-dev @storybook/vue3-vite
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nuxt-app@undefined
npm ERR! Found: storybook@8.0.8
npm ERR! node_modules/storybook
npm ERR!   dev storybook@"8.0.8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer storybook@"^8.3.4" from @storybook/vue3-vite@8.3.4
npm ERR! node_modules/@storybook/vue3-vite
npm ERR!   dev @storybook/vue3-vite@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/.npm/_logs/2024-10-02T16_16_55_032Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-02T16_16_55_032Z-debug-0.log
```

**Comment by tobiasdiez** [comment] 2024-10-02 17:09
Duplicate of https://github.com/nuxt-modules/storybook/issues/767.

Where did you read that `npx storybook-nuxt init` should work?

**Closed by tobiasdiez** 2024-10-02 17:09 UTC
Labels: type: bug

**Comment by erikahumadakandc** [comment] 2024-10-03 00:03
Hey 👋, In the documentation https://storybook.nuxtjs.org/getting-started/setup/ @tobiasdiez

**Comment by erikahumadakandc** [comment] 2024-10-03 00:10
I solved it by updating these packages 
```
npm i -D storybook@latest \
 @storybook/vue3@latest  \
 @storybook-vue/nuxt@latest \
 @storybook/addon-essentials@latest \
 @storybook/addon-interactions@latest \
 @storybook/addon-interactions@latest \
 @storybook/blocks@latest \
 @storybook/builder-vite@latest \
 @storybook/test@latest

```
I removed @types/node package
