### ISSUE TITLE
Getting error: "[nuxt] instance unavailable" if the component uses any nuxt.js-related components

### ISSUE THREAD

**Issue by IvanRozb** [nuxt-modules/storybook#474] opened 2024-01-29 17:33 UTC
![image](https://github.com/nuxt-modules/storybook/assets/79807731/eb9f769f-da52-4ba5-9723-b17587aff05a)
`Error: [nuxt] instance unavailable
  at Bt (/shared_components/shared_components/storybook-static/_nuxt/_plugin-vue_export-helper.tmSU6o7h.js:1:19822))
  at F (/shared_components/shared_components/storybook-static/_nuxt/MyNuxtWelcome.stories.DlreKLsl.js:1:5662))
  at setup (/shared_components/shared_components/storybook-static/_nuxt/MyNuxtWelcome.stories.DlreKLsl.js:1:7431))
  at ht (/shared_components/shared_components/storybook-static/_nuxt/vue.esm-bundler.pcyicgRl.js:13:1374))
  at Uh (/shared_components/shared_components/storybook-static/_nuxt/vue.esm-bundler.pcyicgRl.js:13:54695))
  at qc (/shared_components/shared_components/storybook-static/_nuxt/vue.esm-bundler.pcyicgRl.js:13:54474))
  at W (/shared_components/shared_components/storybook-static/_nuxt/vue.esm-bundler.pcyicgRl.js:13:40976))
  at B (/shared_components/shared_components/storybook-static/_nuxt/vue.esm-bundler.pcyicgRl.js:13:40869))
  at N (/shared_components/shared_components/storybook-static/_nuxt/vue.esm-bundler.pcyicgRl.js:13:37825))`

To reproduce this issue, use these command:

1. `npx nuxi@latest init .`
2. `yarn install`
3. `yarn add -D @nuxtjs/storybook`
4. `yarn run dev` - it will start nuxt app and generate storybook files
5. `yarn run build-storybook`
6. replace the code in stories/MyWelcome.vue `<NuxtWelcome />` with `  <NuxtImg alt="awf" src="https://images.unsplash.com/photo-1566275529824-cca6d008f3da?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cGhvdG98ZW58MHx8MHx8fDA%3D"/>
`

**Comment by tobiasdiez** [comment] 2024-05-01 09:28
Duplicate of https://github.com/storybook-vue/storybook-nuxt/issues/97

**Closed by tobiasdiez** 2024-05-01 09:28 UTC
