### ISSUE TITLE
Description from props jsdoc not appear

### ISSUE THREAD

**Issue by DonThomz** [nuxt-modules/storybook#464] opened 2023-12-18 00:14 UTC
When I write documentation for props in my Vue component, props descriptions don't appear in the doc table in my story. I've tried many times, but it's not working with Nuxt. If I try with a Vue 3 project as the Storybook documentation, it works perfectly.

## Expected Behavior

When i write in my component

```vue
<script setup>
defineProps({
  /**
   * Short description of my prop
   */
  primary: {
    type: Boolean,
    default: false,
  }
})
</script>

<template>
  <button class="my-button">
    <slot></slot>
  </button>
</template>
```

I suppose to have the description "Short description of my prop" into the description

## Current Behavior

The current description of `primary` props doesn't appear, image below : 

<img width="1018" alt="Screenshot 2023-12-18 at 01 04 37" src="https://github.com/nuxt-modules/storybook/assets/60547615/d3464e5b-3a5c-4fca-9072-72391d94aec9">

## Steps to Reproduce

1. Create an empty project nuxt with nuxt-storybook
2. create a component like that MyButton.vue
```vue
<script setup>
defineProps({
  /**
   * Short description of my prop
   */
  primary: {
    type: Boolean,
    default: false,
  }
})
</script>

<template>
  <button class="my-button">
    <slot></slot>
  </button>
</template>
```
and the story
```javascript
import MyButton from './MyButton'

export default {
    title: 'Core/MyButton',
    component: MyButton,
    parameters: {
        docs: {
            description: {
                component: 'Bouton de base',
            },
        },
    },
    argTypes: {
    },
}

const Template = (args) => ({
    components: { MyButton },
    setup() { return { args }; },
    template: '<MyButton v-bind="args">Click me</MyButton>',
});

export const Primary = Template.bind({});
Primary.args = { primary: true,  };
```
3. Start `npm run dev`

## Context (Environment)

package.json
```
"@nuxt/devtools": "latest",
"@nuxtjs/storybook": "7.0.0",
"@storybook-vue/nuxt": "0.2.0",
"@storybook-vue/nuxt-storybook": "^0.0.1-latest.7",
"@storybook/addon-essentials": "7.5.3",
"@storybook/addon-interactions": "7.5.3",
"@storybook/addon-links": "7.5.3",
"@storybook/blocks": "7.5.3",
"@storybook/builder-vite": "7.5.3",
"@storybook/testing-library": "^0.2.0",
"@storybook/vue3": "7.5.3",
"@types/node": "^18.17.5",
"nuxt": "^3.8.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"storybook": "7.5.3",
"vue": "^3.3.12",
"vue-router": "^4.2.5"
```

`.storybook/main.ts`
```javascript
import type { StorybookConfig } from "@storybook-vue/nuxt";

const config: StorybookConfig = {
  stories: [
    "../stories/**/*.mdx",
    "../components/**/*.stories.@(js|jsx|mjs|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook-vue/nuxt",
    options: {},
  },
  docs: {
    autodocs: true,
  },
};
export default config;
```

**Comment by tobiasdiez** [comment] 2024-06-16 11:42
Is this problem still present in the most recent version? We now use storybook v8 which improved vue support, also there were a few fixes related to the docs.

**Comment by mehcode** [comment] 2024-06-16 18:21
I saw this too. The root cause is the vue plugin needs to be the first plugin in the list. This is fixed in main (in the storybook-vue/nuxt package but unreleased).

**Closed** 2024-06-17 01:50 UTC
Labels: type: bug, status: needs info/work
