### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by Renato66** [nuxt-modules/storybook#574] opened 2024-04-29 15:05 UTC
<img width="886" alt="image" src="https://github.com/nuxt-modules/storybook/assets/9284273/e4e05202-10a5-41cc-b65e-0b67a3ea68f1">
Missing static dirs type

**Comment by tobiasdiez** [comment] 2024-04-30 04:36
Essentially a duplicate of https://github.com/storybook-vue/storybook-nuxt/issues/103.

**Closed by tobiasdiez** 2024-04-30 04:36 UTC
