### ISSUE TITLE
At least one <template> or <script> is required in a single file component.

### ISSUE THREAD

**Issue by Matherss** [nuxt-modules/storybook#541] opened 2024-04-17 13:29 UTC
Hello! I get this error when try to use [nuxt-icons](https://www.npmjs.com/package/nuxt-icons) or [svg-sprite](https://nuxt.com/modules/svg-sprite). 

```

Internal server error: At least one <template> or <script> is required in a single file component.
  Plugin: vite:vue
  File: D:/work/project/node_modules/@nuxtjs/svg-sprite/dist/runtime/components/svg-icon.vue
```

package.json
 ```
"devDependencies": {
    "@nuxt/eslint-config": "^0.3.6",
    "@nuxtjs/eslint-config-typescript": "^12.1.0",
    "@nuxtjs/eslint-module": "^4.1.0",
    "@nuxtjs/storybook": "7.0.0",
    "@nuxtjs/stylelint-module": "^5.2.0",
    "@nuxtjs/svg-sprite": "^1.0.2",
    "@storybook-vue/nuxt": "0.2.6",
    "@storybook/addon-essentials": "8.0.0",
    "@storybook/addon-interactions": "8.0.0",
    "@storybook/addon-links": "8.0.0",
    "@storybook/blocks": "8.0.0",
    "@storybook/builder-vite": "8.0.0",
    "@storybook/testing-library": "^0.2.2",
    "@storybook/vue3": "8.0.0",
    "@storybook/vue3-vite": "8.0.0",
    "@types/node": "^18.19.4",
    "eslint": "^8.57.0",
    "nuxt": "^3.11.2",
    "postcss-html": "^1.6.0",
    "sass": "^1.75.0",
    "storybook": "8.0.0",
    "stylelint": "^16.3.1",
    "stylelint-config-recommended-scss": "^14.0.0",
    "stylelint-config-recommended-vue": "^1.5.0",
    "stylelint-config-standard": "^36.0.0",
    "stylelint-order": "^6.0.4",
    "stylelint-scss": "^6.2.1",
    "typescript": "^5.4.5",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.5.1",
    "pinia": "^2.1.7"
  }
```

nuxt.config.ts

```
export default defineNuxtConfig({
  devtools: { enabled: true },
  telemetry: false,

  modules: [
    [
      '@nuxtjs/eslint-module',
      {
        lintOnStart: false
      }
    ],
    '@pinia/nuxt',
    '@nuxtjs/svg-sprite',
    '@nuxtjs/storybook',
    '@nuxtjs/stylelint-module'
  ],
  storybook: {
    modules: {
      exclude: ['@nuxtjs/svg-sprite', 'nuxt-icons', 'svg-sprite']
    }
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/scss/app.scss" as *;'
        }
      }
    }
  }
})
```

As u see i tried to exclude modules from storybook, but i dont know how to do this correctly.
Can you suggest me a solution to this problem?

**Comment by tobiasdiez** [comment] 2024-04-25 09:12
Duplicate of https://github.com/storybook-vue/storybook-nuxt/issues/4

**Closed by tobiasdiez** 2024-04-25 09:12 UTC
